[conversion_error_calling]
  max_number_of_unconv_cytosines = 2

[basic_quality_filtering]
  min_mapq = 1
  min_phred_score = 1

[trimming]
  max_flen_considered_for_trimming = 500
  required_n_events_for_cutting_site_determination = 3000
  max_window_size_for_smoothing = 10

  [trimming.relative_to_fragment_ends]
    W_BC = [0, 9]
    C_BC = [0, 9]
    W_BC_Rv = [9, 0]
    C_BC_Rv = [9, 0]

[data_properties]
  max_read_length_bp = 101

[parallelization]
  pos_per_process = 1000
