[stats]
  max_flen = 500
  max_flen_with_single_flen_resolution = 150
  flen_bin_size = 20
  max_phred = 40
  phred_bin_size = 5
  seq_context_size = 5

[plots]
  mbias_flens_to_display = [60, 75, 90, 100, 120, 150, 190, 290, 490]
  mbias_phreds_to_display = [0, 5, 10, 15, 20, 25, 30, 35, 40]

[conversion_error_calling]
  max_number_of_unconv_cytosines = 2

[basic_quality_filtering]
  min_mapq = 25
  min_phred_score = 25

[trimming]
  min_plateau_perc = 0.5
  max_flen_considered_for_trimming = 500
  min_flen_considered_for_trimming = 50
  max_std_within_plateau = 0.02

  # for customization, you have to give a *complete* new dict
  [trimming.relative_to_fragment_ends_dict]
    w_bc = [0, 9]
    c_bc = [0, 9]
    w_bc_rv = [9, 0]
    c_bc_rv = [9, 0]


[beta_value_dist_stats]
  min_cov = 10
  kde_sigma = 4

[data_properties]
  max_read_length_bp = 150
  min_flen_considered_for_methylation_calling = 30

[parallelization]
  pos_per_process = 1000

[mbias_plots]
    distance_between_displayed_flen = 30

[coverage_analysis]
  max_per_motif_cov = 80

# Paths section must be at end of file!
[paths]
  qc_stats_dir                  = 'qc_stats'
  mbias_counts                  = "{qc_stats_dir}/{name}_mbias-counts_{motifs_str}"
  mbias_stats_trunk             = "{qc_stats_dir}/{name}_mbias-stats_{motifs_str}"
  mbias_stats_p                 = "{qc_stats_dir}/{name}_mbias-stats_{motifs_str}.p"
  mbias_stats_tsv               = "{qc_stats_dir}/{name}_mbias-stats_{motifs_str}.tsv"
  mbias_stats_masked_p          = "{qc_stats_dir}/{name}_mbias-stats_masked_{motifs_str}.p"
  mbias_stats_masked_tsv        = "{qc_stats_dir}/{name}_mbias-stats_masked_{motifs_str}.tsv"
  mbias_stats_classic_p         = "{qc_stats_dir}/{name}_mbias-stats_{motifs_str}_classic.p"
  mbias_stats_phred_threshold_trunk = "{qc_stats_dir}/{name}_mbias-stats_phred-threshold_{motifs_str}.p"
  mbias_stats_masked_phred_threshold_trunk = "{qc_stats_dir}/{name}_mbias-stats_masked_phred-threshold_{motifs_str}.p"
  mbias_stats_heatmap_trunk   = "{qc_stats_dir}/{name}_{motifs_str}_mbias-stats_heatmap"
  adjusted_cutting_sites_obj_p  = "{qc_stats_dir}/{name}_adjusted_cutting_sites_obj_{motifs_str}.p"
  adjusted_cutting_sites_df_p   = "{qc_stats_dir}/{name}_adjusted_cutting_sites_df_{motifs_str}.p"
  adjusted_cutting_sites_df_tsv = "{qc_stats_dir}/{name}_adjusted_cutting_sites_df_{motifs_str}.tsv"
  mbias_plots_trunk             = "{qc_stats_dir}/{name}_mbias-line-plot_{motifs_str}"
  cg_occurence_plot_trunk       = "{qc_stats_dir}/{name}_freq-line-plot_{motifs_str}"
  freq_with_agg_pos_plot        = "{qc_stats_dir}/{name}_freq-agg-pos-plot_{motifs_str}"
  adj_cutting_sites_plot        = "{qc_stats_dir}/{name}_adjusted-cutting-sites_barplot_{motifs_str}.png"
  cov_counts                    = "{qc_stats_dir}/{name}_coverage-counts_{motifs_str}"
  coverage_hist                 = "{qc_stats_dir}/{name}_coverage-hist_{motifs_str}.png"
  meth_calls_basepath           = "meth_calls/mcalls"

