[conversion_error_calling]
  max_number_of_unconv_cytosines = 2

[basic_quality_filtering]
  min_mapq = 25
  min_phred_score = 25

[trimming]
  min_plateau_perc = 0.8
  max_flen_considered_for_trimming = 600
  min_flen_considered_for_trimming = 50
  max_std_within_plateau = 0.02

  # for customization, you have to give a *complete* new dict
  [trimming.relative_to_fragment_ends_dict]
    w_bc = [0, 9]
    c_bc = [0, 9]
    w_bc_rv = [9, 0]
    c_bc_rv = [9, 0]

[plots]
  mbias_flens_to_display = [60, 75, 90, 100, 120, 150, 200, 300, 500]
  mbias_phreds_to_display = [0, 5, 10, 15, 20, 25, 30, 35, 40]

[beta_value_dist_stats]
  min_cov = 10
  kde_sigma = 4

[data_properties]
  max_read_length_bp = 101
  min_flen_considered_for_methylation_calling = 30

[parallelization]
  pos_per_process = 1000

[mbias_plots]
    distance_between_displayed_flen = 30

[coverage_analysis]
  max_per_cpg_cov = 80

# Paths section must be at end of file!
[paths]
  qc_stats_dir                  = 'qc_stats'
  mbias_counts_p                = "{qc_stats_dir}/{name}_mbias-counts_{motifs_str}.p"
  mbias_counts_tsv              = "{qc_stats_dir}/{name}_mbias-counts_{motifs_str}.tsv"
  mbias_stats_p                 = "{qc_stats_dir}/{name}_mbias-stats_{motifs_str}.p"
  mbias_stats_tsv               = "{qc_stats_dir}/{name}_mbias-stats_{motifs_str}.tsv"
  mbias_stats_masked_p          = "{qc_stats_dir}/{name}_mbias-stats_masked_{motifs_str}.p"
  mbias_stats_masked_tsv        = "{qc_stats_dir}/{name}_mbias-stats_masked_{motifs_str}.tsv"
  adjusted_cutting_sites_obj_p  = "{qc_stats_dir}/{name}_adjusted_cutting_sites_obj_{motifs_str}.p"
  adjusted_cutting_sites_df_p   = "{qc_stats_dir}/{name}_adjusted_cutting_sites_df_{motifs_str}.p"
  adjusted_cutting_sites_df_tsv = "{qc_stats_dir}/{name}_adjusted_cutting_sites_df_{motifs_str}.tsv"
  mbias_plots_trunk             = "{qc_stats_dir}/{name}_mbias-line-plot_{motifs_str}"
  cg_occurence_plot_trunk       = "{qc_stats_dir}/{name}_freq-line-plot_{motifs_str}"
  adj_cutting_sites_plot        = "{qc_stats_dir}/{name}_adjusted-cutting-sites_barplot_{motifs_str}.png"
  meth_calls_basepath           = "meth_calls/mcalls"

