[conversion_error_calling]
  max_number_of_unconv_cytosines = 2

[basic_quality_filtering]
  min_mapq = 25
  min_phred_score = 25

[trimming]
  max_flen_considered_for_trimming = 600
  required_n_events_for_cutting_site_determination = 5000
  max_window_size_for_smoothing = 30
  min_plateau_length = 60
  max_std_within_plateau = 0.1
  # Don't use out-of-bounds fragment lengths! (see max_flen/min_flen params)
  flens_to_show_in_plots = [
    50, 70, 80, 90, 100, 110, 130, 150, 200, 250, 300, 350
  ]

  # for customization, you have to give a *complete* new dict
  [trimming.relative_to_fragment_ends_dict]
    w_bc = [0, 9]
    c_bc = [0, 9]
    w_bc_rv = [9, 0]
    c_bc_rv = [9, 0]

[beta_value_dist_stats]
  min_cov = 10
  kde_sigma = 4

[data_properties]
  max_read_length_bp = 101
  min_flen_considered_for_methylation_calling = 30

[parallelization]
  pos_per_process = 1000

[mbias_plots]
    distance_between_displayed_flen = 30

[coverage_analysis]
  max_per_cpg_cov = 80

# Paths section must be at end of file!
[paths]
  [paths.stats]
      qc_stats_dir = "qc_stats"
      mbias_stats_tsv = "{qc_stats_dir}/{name}_mbias-stats_{motifs_str}.tsv"
      mbias_stats_p = "{qc_stats_dir}/{name}_mbias-stats_{motifs_str}.p"
  [paths.call]
      meth_calls_basepath = "meth_calls/mcalls"

